global:
  # 每15s获取一次数据指标
  scrape_interval: 15s
  # 获取数据超时时长 10s
  scrape_timeout: 10s
  # 规则评估评率，即计算指标是否有触发规则的计算频率
  evaluation_interval: 15s

# 规则文件，从所有匹配的文件中读取规则和警报
rule_files:
  - "alert_rules.yml"

# 采集配置列表
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    scrape_interval: 8s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

# Alertmanager的配置
# alerting:
#   alertmanagers:
#   - scheme: http
#     static_configs:
#     - targets:
#       - 'alertmanager:9093'
